<?php

namespace FrontOffice\ClientBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ServiceDemandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceDemandeRepository extends EntityRepository
{
}
