<?php

namespace FrontOffice\StaticBundle\Entity;

use Doctrine\ORM\EntityRepository;
use FrontOffice\StaticBundle\Entity\Responsable as responsable;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponsableRepository extends EntityRepository
{
    public function existResponsable($username,$pass)
    {
        $repository = $this->getEntityManager();

        $query=$repository->createQueryBuilder('r')
            ->from('FrontOffice\StaticBundle\Entity\Responsable','r')
            ->select('r.cin')
            ->where('r.login = :identifier')
            ->andwhere('r.password = :pass')
            ->setParameter('identifier', $username)
            ->setParameter('pass', $pass);
        return $query->getQuery()->getOneOrNullResult();
    }
     public function customizedUpdateWithPicture(responsable $responsable)
        {
            $repository = $this->getEntityManager();
            $query=$repository->createQueryBuilder('r')
                ->update('FrontOffice\StaticBundle\Entity\Responsable','r')
                ->set('r.tel',':tel')
                ->set('r.email',':email')
                ->set('r.photo',':photo')
                ->set('r.login',':login')
                ->set('r.password',':pass')
                ->where('r.cin = :cin')
                ->setParameter('tel', $responsable->getTel())
                ->setParameter('email', $responsable->getEmail())
                ->setParameter('photo', $responsable->getPhoto())
                ->setParameter('login', $responsable->getLogin())
                ->setParameter('pass', $responsable->getPassword())
                ->setParameter('cin', $responsable->getCin());
             return $query->getQuery()->execute();
        }
        public function customizedUpdateWithoutPicture(responsable $responsable)
                {
                    $repository = $this->getEntityManager();
                    $query=$repository->createQueryBuilder('r')
                        ->update('FrontOffice\StaticBundle\Entity\Responsable','r')
                        ->set('r.tel',':tel')
                        ->set('r.email',':email')
                        ->set('r.login',':login')
                        ->set('r.password',':pass')
                        ->where('r.cin = :cin')
                        ->setParameter('tel', $responsable->getTel())
                        ->setParameter('email', $responsable->getEmail())
                        ->setParameter('login', $responsable->getLogin())
                        ->setParameter('pass', $responsable->getPassword())
                        ->setParameter('cin', $responsable->getCin());
                     return $query->getQuery()->execute();
                }
}
