<?php

namespace FrontOffice\ResponsableBundle\Entity\Repo;

use Doctrine\ORM\EntityRepository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends EntityRepository
{
    public function RetrieveServices ($salle)
    {
        $repository = $this->getEntityManager();
        $query=$repository->createQueryBuilder('s')
            ->from('FrontOffice\ResponsableBundle\Entity\Service','s')
            ->select('s')
            ->where('s.salle = :salle')
            ->setParameter('salle', $salle);
        return $query->getQuery()->execute();
    }
}
